# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNewTest():

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_newTest(self):
        self.driver.get("http://172.25.199.63:8080/home/-N3hlfKxXwby0jSSDbxV/team/-NTd4gODlBQPL9Na1VYr/scoring/-NW1TCL0Frg3amRA_EYl")
        self.driver.find_element(By.CSS_SELECTOR, ".team-member:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".d-grid > .d-grid:nth-child(1) > .btn-outline-secondary:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".d-grid:nth-child(2) > .btn").click()
